# Generated by Django 5.2.4 on 2025-11-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('post', models.CharField(default='', max_length=500)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
